### ISSUE TITLE
dbxcli won't install on Macintel w/ Monterrey 12.4

### ISSUE THREAD

**Issue by KirkBrooks** [ThomasMaul/FileTransfer_Class#1]
Authentication process fails:  Bad CPU type in executable

Also tried with BASH - same result. 

Full terminal output: 

kirk@iMac FileTransfer_Class % '/Users/kirk/4D Workspace/git_repos/thomasMaul/FileTransfer_Class/optional/dbxcli_Mac_precompiled/dbxcli' ls
zsh: bad CPU type in executable: /Users/kirk/4D Workspace/git_repos/thomasMaul/FileTransfer_Class/optional/dbxcli_Mac_precompiled/dbxcli
kirk@iMac FileTransfer_Class % sudo '/Users/kirk/4D Workspace/git_repos/thomasMaul/FileTransfer_Class/optional/dbxcli_Mac_precompiled/dbxcli' ls
Password:
sudo: unable to execute /Users/kirk/4D Workspace/git_repos/thomasMaul/FileTransfer_Class/optional/dbxcli_Mac_precompiled/dbxcli: Bad CPU type in executable
kirk@iMac FileTransfer_Class %

**Comment by ThomasMaul** [comment]
oops, thanks for reporting. The precompiled version was build for ARM64, so not running on an Intel based Mac. I've recompiled for Intel, so it will work on both Intel+ARM (using Rosetta).
Also modified the build instructions.
