### ISSUE TITLE
Path 

### ISSUE THREAD

**Issue by karl-voda** [ThomasMaul/FileTransfer_Class#5]
Hallo Herr Maul,

in der Anleitung schreiben Sie zu DropBox, man kann den dxbcli in den Resources-Ordner tun. In der Klasse FileTransfer_Dropbox ist in Zeile 9/12 als Pfad aber nur "dbxcli" oder "dbxcli.exe" angegeben. 
Dadurch werden Fehlermeldungen (nicht) geworfen (weil unterdrückt) und die Klasse funktioniert so nicht.

Idee: 
Z. 9: This._Path:=Get 4D folder(Current resources folder)+"dbxcli"
Z. 12: Get 4D folder(Current resources folder)+"dbxcli.exe"

Unter Windows funktioniert jedenfalls dadurch jetzt schon mal getDirectoryListing($target)

Viele Grüße
Heiko Junghärtchen

**Comment by ThomasMaul** [comment]
Hallo,
in der Testmethode "testdropbox" wurde der Pfad gesetzt:
$ftp.setPath(" /Users/thomas/Desktop/dbxcli")
eigentlich weiß ich nicht, wie/wo dbxcli installiert ist, aber letztlich haben Sie Recht, im Resource Ordner prüfen schadet auch nichts.
Ich prüfe jetzt ob es im Resource-Ordner einen Ordner Dropbox gibt und darin dbxcli liegt (Pfad wie bei GDrive). Wenn ja, nehme ich den, wenn nein bleibe ich beim alten Namen (um die Kompatibilität sicherzustellen).

Danke für den Hinweis.
