### ISSUE TITLE
Error during renaming with the FileTransfer_CURL class in SFTP

### ISSUE THREAD

**Issue by backimg2018** [ThomasMaul/FileTransfer_Class#7]
Hello Thomas,

Thank you for this class suite, it really makes our SFTP transfers much easier.

It seems that there is an error in the FileTransfer_CURL.4DM file, line 228, where renaming does not work.
There is an extra quotation mark between the two paths in the RENAME function.
The functional correction is:
$url:=$url+" -Q "+Char:C90(34)+"-RENAME "+$sourcepath+" "+$targetpath+Char:C90(34)

Best regards

**Comment by ThomasMaul** [comment]
thanks for your report, fixed (and uploaded as notarized build) in 1.1.2
