### ISSUE TITLE
Compilation Bug V1.1.2

### ISSUE THREAD

**Issue by backimg2018** [ThomasMaul/FileTransfer_Class#8]
Hello Thomas,
Thank you for your prompt correction.
I believe there is a compilation error. I am encountering a compilation error message when using the component, an issue I didn’t have with version 1.1.1.
This is the first time I am using a component, so I don’t have the necessary knowledge to recompile everything.
For your information, I am using 4D 20.4 LTS

![image](https://github.com/user-attachments/assets/6e18d6f8-7d2a-4c21-b3ed-32d4fe152256)

**Comment by ThomasMaul** [comment]
Yes, sorry for that. The component requires 4D 20 R5 or newer.
It uses a class _build with a project method to build the component. Build covers compiler, build, sign and notarize with Apple. This method is using language extensions introduced after 20 LTS, so not possible to compile it with 20 LTS.

You can either use the previous version (and fix the Rename line yourself, it is just removing the char(34) in the middle of the line, as you detected already or use this version, remove the build class and build method and compile yourself, then build using the build application dialog. Then the component is not notarized, you can still use it on your own Mac (as you compiled yourself), if you distribute your final application you need to sign/notarize the application anyway, which will include the component.

**Comment by ThomasMaul** [comment]
I've updated release notes and read me to inform about R5 as minimum
